In [ ]:
#Syntax
#pip install pip
#check if pip is installed by writing
#pip-version
#pip uninstall package name

In [7]:
pip install numpy
!pip install numpy

In [9]:
pip install pandas
import pandas as pd

SyntaxError: invalid syntax (3716164084.py, line 1)

In [15]:
pip--version


pip 24.0 from C:\Users\User\anaconda3\Lib\site-packages\pip (python 3.12)

Note: you may need to restart the kernel to use updated packages.


In [17]:
lst=[1,2,3,4,5]
np_arr=numpy.array(lst)
np_arr
array([1,2,3,4,5])
len(np_arr)
5
np_arr*2
array([2,4,6,8,10])
np_arr+2
array([3,4,5,6,7])

NameError: name 'numpy' is not defined

In [25]:
import webbrowser # web browser module to open websites
# list of urls:python
url_lists=[
    'https://www.python.org',
    'https://www.linkediin.com/in/Raju/',
    'https://github.com/Raju',
    'https://twitter.com/Raju',
]
#opens the above list of websites in a different tab
for url in url_lists:
    webbrowser.open_new_tab(url)

In [37]:
from bs4 import BeautifulSoup as BS
import requests
url = "https://economictimes.indiatimes.com/commoditysummary/symbol-GOLD.cms"
date=[]
price=[]
data=requests.get(url)
soup=BS(data.text,'html.parser')
dat=soup.find("p",class_="datetime").text.strip()
dat
'12:0PM IST | 03 Sep, 2024'

'12:0PM IST | 03 Sep, 2024'

In [ ]:
from bs4 import BeautifulSoup as BS
import requests
url = "https://economictimes.indiatimes.com/commoditysummary/symbol-GOLD.cms"
date=[]
price=[]
data=requests.get(url)
soup=BS(data.text,'html.parser')
soup

In [22]:
import pandas as pd
import numpy as np
table = pd.read_excel(r"C:\Users\User\Downloads\IBM-313 Marks.xlsx")
print(table)

    S.No.  MTE (25)  Mini Project (25)  Total (50)  ETE (50)  Total
0       1      5.00                 20       25.00      12.0  37.00
1       2     11.05                 20       31.05      26.0  57.05
2       3      8.10                 20       28.10      14.0  42.10
3       4      6.00                 10       16.00      13.0  29.00
4       5     11.35                 20       31.35      17.0  48.35
..    ...       ...                ...         ...       ...    ...
74     75     12.05                 10       22.05      20.0  42.05
75     76     12.25                 10       22.25      28.0  50.25
76     77      1.75                 10       11.75       NaN   0.00
77     78      3.00                 10       13.00       NaN   0.00
78     79      5.80                 10       15.80      12.0  27.80

[79 rows x 6 columns]


In [34]:
#mean
x=table['Total']
np.mean(x)


46.90632911392405

In [36]:
#mean
x=table['Total']
np.median(x)

45.0

In [38]:
#mean
x=table['Total']
x.mode()

0     0.00
1    38.00
2    39.70
3    41.00
4    42.70
5    43.50
6    48.35
Name: Total, dtype: float64

In [40]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [42]:
#percentile
a=np.array([1,2,3,4,5])
p=np.percentile(a,50) #return 50th percentile, eg median
print(p)

3.0


In [44]:
#example of for loop
k = ['Ram',65,2.5]
print(k)

['Ram', 65, 2.5]


In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [52]:
df=pd.read_csv(r"C:\Users\User\Downloads\five year dataset.csv")
